spring:
  datasource:
    password: sa
    url: jdbc:postgresql://localhost:5432/db
    username: sa
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
      # SQL logging
  #                show_sql: true
  #                format_sql: false
  flyway:
    user: sa
    password: sa
    url: jdbc:postgresql://localhost:5432/db
    locations: classpath:db/migration
    enabled: true

server:
  port: ${SERVER_PORT:8585}

auth.secret: JSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2